version: '3'
services:
  mongodb:
    image: mongo:5.0.3
    restart: always
    ports:
      - 27100:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
